name: build-client
on:
  push:
    paths:
      - "apps/client/**"
      - "packages/database/**"

jobs:
  Run-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          npm install -g pnpm@8.9.0
          pnpm install

      - name: Build
        env:
          NEXT_PUBLIC_KAKOMAP_KEY: ${{ secrets.NEXT_PUBLIC_KAKOMAP_KEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MSG_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MSG_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: pnpm build:client
